import { MigrationInterface, QueryRunner } from "typeorm";

export class 1700000000000AdminUsersCitiesZones1769947184561 implements MigrationInterface {
    name = '1700000000000AdminUsersCitiesZones1769947184561'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP CONSTRAINT "delivery_events_delivery_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drivers_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drivers_city_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_drivers_zone_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_delivery_events_seller_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deliveries_seller_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deliveries_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_deliveries_driver"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_seller_driver"`);
        await queryRunner.query(`CREATE TYPE "public"."admin_users_role_enum" AS ENUM('DRIVER', 'ADMIN', 'SUPER_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "admin_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "role" "public"."admin_users_role_enum" NOT NULL DEFAULT 'ADMIN', "is_active" boolean NOT NULL DEFAULT true, "city_id" uuid, "created_by_id" character varying, "last_login_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dcd0c8a4b10af9c986e510b9ecc" UNIQUE ("email"), CONSTRAINT "PK_06744d221bb6145dc61e5dc441d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71bd654a40110dd404847b1b87" ON "admin_users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_ebd44622c0e2e69538e2daa5ad" ON "admin_users" ("city_id") `);
        await queryRunner.query(`CREATE TABLE "cities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "center" point, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4762ffb6e5d198cfec5606bc11e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "zones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "city_id" uuid NOT NULL, "boundary" polygon, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_880484a43ca311707b05895bd4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "driver_offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deliveryId" uuid NOT NULL, "driverId" uuid NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "offerPayload" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, "acceptedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "rejectionReason" text, "notificationSentAt" TIMESTAMP, "notificationMethod" character varying(20) NOT NULL DEFAULT 'push', "driverResponseTimeMs" integer, CONSTRAINT "PK_c0dcc29d68fd72391d9add29634" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_delivery_pending" ON "driver_offers" ("deliveryId") `);
        await queryRunner.query(`CREATE INDEX "idx_driver_pending" ON "driver_offers" ("driverId") `);
        await queryRunner.query(`CREATE INDEX "idx_expires_at" ON "driver_offers" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "idx_created_at" ON "driver_offers" ("notificationSentAt") `);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "delivery_id"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "seller_order_id"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "event_type"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "proof_url"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "failure_code"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "failure_reason"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "seller_order_id"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "channel_id"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "driver_id"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "pickup_lat"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "pickup_lon"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "drop_lat"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "drop_lon"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "pickup_proof_url"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "delivery_proof_url"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "failure_code"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "failure_reason"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "picked_up_at"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "delivered_at"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "failed_at"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "seller_order_id"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "driver_id"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "deliveryId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "sellerOrderId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "eventType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "proofUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "failureCode" character varying`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "failureReason" character varying`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "sellerOrderId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "channelId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "driverId" character varying`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "pickupLat" numeric(10,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "pickupLon" numeric(11,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "dropLat" numeric(10,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "dropLon" numeric(11,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "pickupProofUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "deliveryProofUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "failureCode" character varying`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "failureReason" character varying`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "assignedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "pickedUpAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "deliveredAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "failedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "sellerOrderId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "driverId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "drivers_phone_key"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "UQ_b97a5a68c766d2d1ec25e6a85b2" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_status_enum" AS ENUM('AVAILABLE', 'BUSY', 'OFFLINE')`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "status" "public"."drivers_status_enum" NOT NULL DEFAULT 'AVAILABLE'`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "current_lat" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "current_lon" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "vehicle_type"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "vehicle_type" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "vehicle_number"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "vehicle_number" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "status" character varying NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`CREATE INDEX "IDX_c8dfd450587b08627f347f6f5e" ON "drivers" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_dae9223023a6734f8763c7cf16" ON "drivers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_049be208a520d774555b6f2577" ON "drivers" ("city_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_582c992c4f9f06a3fa398a2e92" ON "drivers" ("zone_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_da866d681a7c573ceca820fb00" ON "delivery_events" ("sellerOrderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4e51215b884ad6050a1668890" ON "delivery_events" ("deliveryId", "eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6cc84e1c957ed2d25bd7eda4b" ON "deliveries" ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3235c9c06d9d3028a11ec8081d" ON "deliveries" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f968926f91f87db1e8f97d15b0" ON "deliveries" ("sellerOrderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d25f86c62a0ddbfc1fa81ca8ba" ON "assignments" ("sellerOrderId", "driverId") `);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD CONSTRAINT "FK_ebd44622c0e2e69538e2daa5ade" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zones" ADD CONSTRAINT "FK_cd00194405d6fd971c4b3b3b788" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD CONSTRAINT "FK_d9d6854f149404b24407f0531c4" FOREIGN KEY ("deliveryId") REFERENCES "deliveries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP CONSTRAINT "FK_d9d6854f149404b24407f0531c4"`);
        await queryRunner.query(`ALTER TABLE "zones" DROP CONSTRAINT "FK_cd00194405d6fd971c4b3b3b788"`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP CONSTRAINT "FK_ebd44622c0e2e69538e2daa5ade"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d25f86c62a0ddbfc1fa81ca8ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f968926f91f87db1e8f97d15b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3235c9c06d9d3028a11ec8081d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6cc84e1c957ed2d25bd7eda4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4e51215b884ad6050a1668890"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da866d681a7c573ceca820fb00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_582c992c4f9f06a3fa398a2e92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_049be208a520d774555b6f2577"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dae9223023a6734f8763c7cf16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8dfd450587b08627f347f6f5e"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "status" character varying(20) DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "vehicle_number"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "vehicle_number" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "vehicle_type"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "vehicle_type" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "current_lon" TYPE numeric(11,8)`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "current_lat" TYPE numeric(10,8)`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "status" character varying(20) DEFAULT 'AVAILABLE'`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "UQ_b97a5a68c766d2d1ec25e6a85b2"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "phone" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "drivers_phone_key" UNIQUE ("phone")`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP COLUMN "sellerOrderId"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "failedAt"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "deliveredAt"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "pickedUpAt"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "assignedAt"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "failureReason"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "failureCode"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "deliveryProofUrl"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "pickupProofUrl"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "dropLon"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "dropLat"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "pickupLon"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "pickupLat"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "driverId"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "channelId"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP COLUMN "sellerOrderId"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "failureReason"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "failureCode"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "proofUrl"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "eventType"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "sellerOrderId"`);
        await queryRunner.query(`ALTER TABLE "delivery_events" DROP COLUMN "deliveryId"`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "driver_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD "seller_order_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "failed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "delivered_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "picked_up_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "assigned_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "failure_reason" text`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "failure_code" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "delivery_proof_url" text`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "pickup_proof_url" text`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "drop_lon" numeric(11,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "drop_lat" numeric(10,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "pickup_lon" numeric(11,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "pickup_lat" numeric(10,8) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "driver_id" uuid`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "channel_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD "seller_order_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "failure_reason" text`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "failure_code" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "proof_url" text`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "event_type" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "seller_order_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD "delivery_id" uuid NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_driver_pending"`);
        await queryRunner.query(`DROP INDEX "public"."idx_delivery_pending"`);
        await queryRunner.query(`DROP TABLE "driver_offers"`);
        await queryRunner.query(`DROP TABLE "zones"`);
        await queryRunner.query(`DROP TABLE "cities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebd44622c0e2e69538e2daa5ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71bd654a40110dd404847b1b87"`);
        await queryRunner.query(`DROP TABLE "admin_users"`);
        await queryRunner.query(`DROP TYPE "public"."admin_users_role_enum"`);
        await queryRunner.query(`CREATE INDEX "idx_assignments_seller_driver" ON "assignments" ("seller_order_id", "driver_id") `);
        await queryRunner.query(`CREATE INDEX "idx_deliveries_driver" ON "deliveries" ("driver_id") `);
        await queryRunner.query(`CREATE INDEX "idx_deliveries_status" ON "deliveries" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_deliveries_seller_order" ON "deliveries" ("seller_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_delivery_events_seller_order" ON "delivery_events" ("seller_order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_drivers_zone_id" ON "drivers" ("zone_id") `);
        await queryRunner.query(`CREATE INDEX "idx_drivers_city_id" ON "drivers" ("city_id") `);
        await queryRunner.query(`CREATE INDEX "idx_drivers_status" ON "drivers" ("status") `);
        await queryRunner.query(`ALTER TABLE "delivery_events" ADD CONSTRAINT "delivery_events_delivery_id_fkey" FOREIGN KEY ("delivery_id") REFERENCES "deliveries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
