#!/usr/bin/env bash
# scripts/db-cleanup-companions.sh
#
# ONE-TIME cleanup script for the 33 OutboxEnhancements companion files
# generated before the migrate.ts fixes were applied.
#
# These files cannot be applied because:
#   1. They fail governance (no bypass annotations)
#   2. They were generated by the broken rewriteNotNullViolations regex
#      which fired on every ADD COLUMN ... NOT NULL DEFAULT even though
#      PostgreSQL ≥11 handles those safely without a table rewrite.
#   3. They represent 33 tiny single-statement migrations instead of
#      one clean schema alignment migration.
#
# SAFE TO RUN: these files have NOT been applied to the database
# (npm run db:migrate failed before reaching the apply step).
# Confirmed: db:drift shows them as "pending" — they are only in the
# filesystem, not in the _migrations table.
#
# After running this script:
#   1. Apply the migrate.ts patch (PATCH_migrate.ts.comments.ts)
#   2. Run: npm run db:new -- SchemaAlignment
#   3. Review the generated file — it will be a single BREAKING_ with bypass annotations
#   4. Run: npm run db:migrate

set -e

MIGRATIONS_DIR="./src/migrations"

echo "🧹 Cleaning up auto-generated OutboxEnhancements companion files..."
echo ""

# Count files that will be deleted
COUNT=$(find "$MIGRATIONS_DIR" -name "*OutboxEnhancements*" -o -name "*AutoMigration*" 2>/dev/null | wc -l | tr -d ' ')

if [ "$COUNT" -eq 0 ]; then
  echo "✅ No companion files found — nothing to clean up"
  exit 0
fi

echo "  Found $COUNT file(s) to delete:"
find "$MIGRATIONS_DIR" -name "*OutboxEnhancements*" -o -name "*AutoMigration*" 2>/dev/null | sort | while read -r f; do
  echo "    • $(basename "$f")"
done

echo ""
read -p "  Delete these $COUNT file(s)? [y/N] " confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
  echo "  Aborted."
  exit 1
fi

find "$MIGRATIONS_DIR" \( -name "*OutboxEnhancements*" -o -name "*AutoMigration*" \) -delete

echo ""
echo "✅ Deleted $COUNT companion file(s)"
echo ""
echo "Next steps:"
echo "  1. Apply the migrate.ts patch (see PATCH_migrate.ts.comments.ts)"
echo "  2. npm run db:new -- SchemaAlignment"
echo "  3. Review the generated migration SQL"  
echo "  4. npm run db:migrate"